/*
 * Copyright (C) 2011 MineStar.de 
 * 
 * This file is part of MineStarLibrary.
 * 
 * MineStarLibrary is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 * 
 * MineStarLibrary is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with MineStarLibrary.  If not, see <http://www.gnu.org/licenses/>.
 */

package de.minestar.minestarlibrary.commands;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map.Entry;

import org.bukkit.command.CommandSender;
import org.bukkit.command.ConsoleCommandSender;
import org.bukkit.entity.Player;

import de.minestar.minestarlibrary.utils.ConsoleUtils;
import de.minestar.minestarlibrary.utils.PlayerUtils;

public class CommandList {

    // The commands are stored in this list. The key indicates the
    // commandssyntax and the argument counter
    private HashMap<String, AbstractCommand> commandList;
    private String pluginName = "";

    /**
     * Creates an array where the commands are stored in and add them all to the
     * HashMap
     * 
     * @param commands
     *            A list of all commands the plugin is using
     */
    public CommandList(AbstractCommand... commands) {
        initCommandList(commands);
    }

    /**
     * Creates an array where the commands are stored in and add them all to the
     * HashMap
     * 
     * @param pluginName
     *            The pluginName for the use of prefixes
     * @param commands
     *            A list of all commands the plugin is using
     */
    public CommandList(String pluginName, AbstractCommand[] commands) {
        this(commands);
        this.pluginName = pluginName;

    }

    /**
     * Use this methode in your java plugins method 'onCommand' to handle all
     * commands
     * 
     * @param sender
     * @param label
     * @param args
     */
    public void handleCommand(CommandSender sender, String label, String[] args) {
        if (!label.startsWith("/"))
            label = "/" + label;

        // looking for non extended and non super command
        AbstractCommand cmd = commandList.get(label + "_" + args.length);
        if (cmd != null)
            cmd.run(args, sender);

        else {
            // look for extended commands and super commands
            cmd = commandList.get(label);
            if (cmd != null)
                cmd.run(args, sender);

            // COMMAND NOT FOUND
            else {
                // Player executed command
                if (sender instanceof Player)
                    PlayerUtils.sendError((Player) sender, pluginName, "Command '" + label + "' not found.");
                // Console executed command
                else if (sender instanceof ConsoleCommandSender)
                    ConsoleUtils.printError("Command '" + label + "' not found!", pluginName);

                // FIND RELATED COMMANDS
                LinkedList<AbstractCommand> cmdList = new LinkedList<AbstractCommand>();
                for (Entry<String, AbstractCommand> entry : commandList.entrySet()) {
                    if (entry.getKey().startsWith(label))
                        cmdList.add(entry.getValue());
                }

                if (sender instanceof Player) {
                    Player player = (Player) sender;
                    for (AbstractCommand command : cmdList)
                        PlayerUtils.sendInfo(player, pluginName, command.getSyntax() + " " + command.getArguments());

                } else if (sender instanceof ConsoleCommandSender) {
                    for (AbstractCommand command : cmdList)
                        ConsoleUtils.printInfo(command.getSyntax() + " " + command.getArguments(), pluginName);
                }
            }
        }
    }
    /**
     * Stores the commands from the array to a HashMap. The key is generated by
     * the followning: <br>
     * <code>syntax_numberOfArguments</code> <br>
     * Example: /warp create_1 (because create has one argument)
     * 
     * @param cmds
     *            The array list for commands
     */
    private void initCommandList(AbstractCommand[] cmds) {

        commandList = new HashMap<String, AbstractCommand>();
        for (AbstractCommand cmd : cmds) {
            String key = "";
            // when the command has a variable count of arguments or
            // when the command has sub commands
            if (cmd instanceof AbstractExtendedCommand || cmd instanceof AbstractSuperCommand)
                key = cmd.getSyntax();
            // a normal command(no subcommands/fix argument count)
            else
                key = cmd.getSyntax() + "_" + cmd.getArgumentCount();

            commandList.put(key, cmd);
        }
    }
}
